name: Update README with Stats

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          username: cahian
          show_icons: true
          include_all_commits: true
          count_private: true
          output_path: ./github-stats.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add github-stats.svg
          git commit -m "update github stats"
          git push
